In [1]:
print('hello')

hello


In [2]:
import numpy as np 
sales = [0,5,155,0,518,0,1827,616,317,325]

sales_array = np.array(sales)
sales_array

array([   0,    5,  155,    0,  518,    0, 1827,  616,  317,  325])

#### Numpy array properties

- ndim - the number of dimensions (axes) in the array 
- shape - the size of the array for each dimension 
- size - the total number of elements in the array 
- dtype - the data type of the elements in the array

In [4]:
import numpy as np 
sales = [0,5,155,0,518,0,1827,616,317,325]

sales_array = np.array(sales)

type(sales_array)

numpy.ndarray

In [5]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")

ndim: 1
shape: (10,)
size: 10
dtype: int64


#### 2 dima array

In [7]:
sales = [[0,5,155,0,518],[0,1827,616,317,325]]
sales_array = np.array(sales)
sales_array

array([[   0,    5,  155,    0,  518],
       [   0, 1827,  616,  317,  325]])

In [8]:
print(f"ndim: {sales_array.ndim}")
print(f"shape: {sales_array.shape}")
print(f"size: {sales_array.size}")
print(f"dtype: {sales_array.dtype}")

ndim: 2
shape: (2, 5)
size: 10
dtype: int64


In [12]:
import numpy as np 
array = np.array(range(5))
array

array([0, 1, 2, 3, 4])

In [16]:
array_2d = np.array([range(5),range(5)])
array_2d

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [17]:
# array_2d+1

In [18]:
array.shape

(5,)

In [19]:
array_2d.shape

(2, 5)

In [20]:
array.size

5

In [21]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [23]:
array_2d.T.shape

(5, 2)

In [24]:
array_2d.ndim

2

In [27]:
np.array(["I", "Love" , "Python"])

array(['I', 'Love', 'Python'], dtype='<U6')

# Assignment: Array Basic

![alt text](<../Attachments/Screenshot 2026-07-04 at 20-09-47 Challenge Array basics LinkedIn Learning.png>)

In [32]:
my_list = [x*10 for x in range(1,11)]
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [33]:
print(f"ndim: {my_array.ndim}")
print(f"shape: {my_array.shape}")
print(f"size: {my_array.size}")
print(f"dtype: {my_array.dtype}")

ndim: 1
shape: (10,)
size: 10
dtype: int64


#### Reshape array

In [40]:
import numpy as np 
array = np.array(range(6))
array

array([0, 1, 2, 3, 4, 5])

In [41]:
array = np.array(range(6)).reshape(1,6)
array

array([[0, 1, 2, 3, 4, 5]])

In [43]:
array = np.array(range(6)).reshape(6,1)
array

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [44]:
array = np.array(range(6)).reshape(3,2)
array

array([[0, 1],
       [2, 3],
       [4, 5]])

# Array Creation
![alt text](<../Attachments/Screenshot 2026-07-04 at 20-18-51 Array creation LinkedIn Learning.png>)


In [49]:
np.ones(4)

array([1., 1., 1., 1.])

In [48]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
np.zeros((2,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [57]:
np.arange(1,9,2)

array([1, 3, 5, 7])

In [58]:
np.arange(1,9,2).reshape(2,2)

array([[1, 3],
       [5, 7]])

# Random Number Array
![alt text](<../Attachments/Screenshot 2026-07-04 at 21-56-48 Random number generation LinkedIn Learning.png>)

In [63]:
from numpy.random import default_rng

rng = default_rng(seed=42)
random_array = rng.random(10)
random_array

array([0.77395605, 0.43887844, 0.85859792, 0.69736803, 0.09417735,
       0.97562235, 0.7611397 , 0.78606431, 0.12811363, 0.45038594])

In [66]:
from numpy.random import default_rng 

rng = default_rng(seed=42)
mean, std = 5, 1
random_array = rng.normal(mean,std,size=10)
random_array

array([5.30471708, 3.96001589, 5.7504512 , 5.94056472, 3.04896481,
       3.69782049, 5.1278404 , 4.68375741, 4.98319884, 4.14695607])

# Assignment : Array Creation

![alt text](<../Attachments/Screenshot 2026-07-04 at 22-04-02 Challenge Array creation LinkedIn Learning.png>)

In [80]:
# my answer
np_array=np.linspace(10,100,10).reshape(5,2)
np_array

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [87]:
# another way
np_array = np.arange(10,101,10).reshape(5,2)
np_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [96]:
# another way

np_array = (np.arange(1,11)*10).reshape(5,2)
np_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [ ]:
# my answer
from numpy.random import default_rng 

rng = default_rng(2022)

# random_array = rng.random((3,3))
random_array = rng.random(9).reshape(3,3)
random_array

array([[0.24742606, 0.09299006, 0.61176337],
       [0.06066207, 0.66103343, 0.75515778],
       [0.1108689 , 0.04305584, 0.41441747]])